optimization

diff --git a/.azure/templates/build.yaml b/.azure/templates/build.yaml
--- a/.azure/templates/build.yaml
+++ b/.azure/templates/build.yaml
@@ -42,42 +42,48 @@ steps:
 
       cwd=`pwd`
 
-      for parentDir in ${cwd}/*/; do
-        for dir in ${parentDir}/*/; do
-          if [ -d ${dir} ]; then
-            dir=${dir%*/}
-            dirName=${dir##*/}
+      # Define known document directories and their site subdirectories
+      declare -A SITE_DIRS=(
+        ["developer-docs"]="developer"
+        ["pe-docs"]="platform-engineer"
+      )
+
+      # Process only the directories we care about
+      for doc_dir in "${!SITE_DIRS[@]}"; do
+        echo "Processing ${doc_dir}..."
+        # Find the parent directory containing this doc directory
+        for parentDir in ${cwd}/*/; do
+          if [ -d "${parentDir}${doc_dir}" ]; then
             parentDir=${parentDir%*/}
             parentDirName=${parentDir##*/}
-            if [ ${dirName} != "dist" ]; then
-            mkdir -p $(Build.ArtifactStagingDirectory)/dist/${dirName}
-            cd ${dir}
-
+            
+            # Create destination directory
+            mkdir -p $(Build.ArtifactStagingDirectory)/dist/${doc_dir}
+            
+            # Build the documentation
+            cd "${parentDir}/${doc_dir}"
             pwd
-            mkdocs build -c -v
-            siteDirName=
-            cd ../../..
-            echo "parentdir ${dirName}"
-            if [ ${dirName} == "developer-docs" ]; then
-              siteDirName="developer"
-            elif [ ${dirName} == "pe-docs" ]; then
-              siteDirName="platform-engineer"
-            fi
-            ls ${cwd}/${parentDirName}/${dirName}/site/${siteDirName}/
-            mv -f ${cwd}/${parentDirName}/${dirName}/site/${siteDirName}/* $(Build.ArtifactStagingDirectory)/dist/${dirName}/
-            fi
+            mkdocs build -c
+            
+            # Move the built files to the staging directory
+            site_subdir="${SITE_DIRS[${doc_dir}]}"
+            echo "Moving files from site/${site_subdir}/ to dist/${doc_dir}/"
+            ls "${cwd}/${parentDirName}/${doc_dir}/site/${site_subdir}/"
+            mv -f "${cwd}/${parentDirName}/${doc_dir}/site/${site_subdir}"/* $(Build.ArtifactStagingDirectory)/dist/${doc_dir}/
+            
+            # Return to the original directory
+            cd "${cwd}"
+            break
           fi
         done
       done
 
       echo "=== After building ==="
-      ls -l $(Build.ArtifactStagingDirectory)/dist/developer-docs
-      if [ -z "$(ls -A $(Build.ArtifactStagingDirectory)/dist/developer-docs)" ]; then
-        echo "Error: developer-docs directory is empty."
-        exit 1
-      fi
-      ls -l $(Build.ArtifactStagingDirectory)/dist/pe-docs
-      if [ -z "$(ls -A $(Build.ArtifactStagingDirectory)/dist/pe-docs)" ]; then
-        echo "Error: pe-docs directory is empty."
-        exit 1
-      fi
+      # Check that the expected directories have content
+      for doc_dir in "${!SITE_DIRS[@]}"; do
+        ls -l $(Build.ArtifactStagingDirectory)/dist/${doc_dir}
+        if [ -z "$(ls -A $(Build.ArtifactStagingDirectory)/dist/${doc_dir})" ]; then
+          echo "Error: ${doc_dir} directory is empty."
+          exit 1
+        fi
+      done
