temp commit

diff --git a/.azure/templates/build.yaml b/.azure/templates/build.yaml
--- a/.azure/templates/build.yaml
+++ b/.azure/templates/build.yaml
@@ -47,18 +47,24 @@ steps:
           if [ -d ${dir} ]; then
             dir=${dir%*/}
             dirName=${dir##*/}
-            parendDir=${dir%*/}
+            parentDir=${parentDir%*/}
             parentDirName=${parentDir##*/}
             if [ ${dirName} != "dist" ]; then
-            mkdir -p $(Build.ArtifactStagingDirectory)/dist/${parentDir}/${dirName}
+            mkdir -p $(Build.ArtifactStagingDirectory)/dist/${dirName}
             cd ${dir}
 
             pwd
-            mkdocs build -c
-
+            mkdocs build -c -v
+            siteDirName=
             cd ../../..
-            ls ${cwd}/${parentDir}/${dirName}/site/
-            mv -f ${cwd}/${parentDir}/${dirName}/site/* $(Build.ArtifactStagingDirectory)/dist/${parentDir}/${dirName}/
+            echo "parentdir ${dirName}"
+            if [ ${dirName} == "developer-docs" ]; then
+              siteDirName="developer"
+            elif [ ${dirName} == "pe-docs" ]; then
+              siteDirName="platform-engineer"
+            fi
+            ls ${cwd}/${parentDirName}/${dirName}/site/${siteDirName}/
+            mv -f ${cwd}/${parentDirName}/${dirName}/site/${siteDirName}/* $(Build.ArtifactStagingDirectory)/dist/${dirName}/
             fi
           fi
         done
@@ -66,4 +72,12 @@ steps:
 
       echo "=== After building ==="
       ls -l $(Build.ArtifactStagingDirectory)/dist/developer-docs
+      if [ -z "$(ls -A $(Build.ArtifactStagingDirectory)/dist/developer-docs)" ]; then
+        echo "Error: developer-docs directory is empty."
+        exit 1
+      fi
       ls -l $(Build.ArtifactStagingDirectory)/dist/pe-docs
+      if [ -z "$(ls -A $(Build.ArtifactStagingDirectory)/dist/pe-docs)" ]; then
+        echo "Error: pe-docs directory is empty."
+        exit 1
+      fi
